version: '3.8'

services:
  eps-ai-web:
    container_name: eps-ai-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
        NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET}
        NEXT_PUBLIC_SANITY_API_VERSION: ${NEXT_PUBLIC_SANITY_API_VERSION}
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Security: Nie kopiujemy kodu, tylko zmienne Å›rodowiskowe
    env_file:
      - .env.local